services:
    web:
        image: bgapp_web:1.0
        ports:
            - 8080:80
        # volumes:
        #     - "/home/vagrant/bgapp/web:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: bgapp_db:1.0
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
networks:
    app-network:
